---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/features
  label: Features
  create: documents
  match: "**/*.md"
  templates:
  - features
- type: directory
  path: content/pricing/pricing-plans
  label: Pricing Plans
  create: documents
  match: "**/*.md"
  templates:
  - pricing-plans
- type: directory
  path: content/pricing/pricing-features
  label: Pricing Features
  create: documents
  match: "**/*.md"
  templates:
  - pricing-features
- type: directory
  path: content/common/footer-rights
  label: Footer Rights
  create: documents
  match: "**/*.md"
  templates:
  - footer-rights
- type: directory
  path: content/common/footer-policies
  label: Footer Policies
  create: documents
  match: "**/*.md"
  templates:
  - footer-policies
- type: directory
  path: content/common/footer-links
  label: Footer Links
  create: documents
  match: "**/*.md"
  templates:
  - footer-links
- type: directory
  path: content/common
  label: It All Begins Here
  create: documents
  match: "**/*.md"
  templates:
  - it-all-begins-here
- type: directory
  path: content/home-testimonials
  label: Home Testimonials
  create: all
  match: "**/*.md"
  templates:
  - home-testimonials
- type: directory
  path: content/home-steps
  label: Home Steps
  create: documents
  match: "**/*.md"
  templates:
  - home-steps-list
- type: directory
  path: content/home-steps/header
  label: Home Steps Header
  create: documents
  match: "**/*.md"
  templates:
  - home-steps-header
- type: directory
  path: content/home-hero
  label: Home Hero Banner
  create: documents
  match: "**/*.md"
  templates:
  - home-hero-banner
- type: directory
  path: content/home-features
  label: Home Features
  create: documents
  match: "**/*.md"
  templates:
  - home-features
upload_dir: static/images
public_path: images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
